Skip manage_snapshot in CNTT
As detected by Orange's RC Field trial, Ceph doesn't support this
feature before Rocky [1].
"AttributeError: 'RBDDriver' object has no attribute 'unmanage_snapshot'"

manage_snapshot testing is fully passing in Functest SUT because CNTT
is verified vs OpenStack Rocky and newer.

Ceph is selected by RI as backend and is widely reused by the ecosystem.
It's similar to [2].

manage_snapshot will be mandatory back once CNTT selects Rocky or newer.

[1] https://bugs.launchpad.net/cinder/+bug/1645288
[2] https://gerrit.opnfv.org/gerrit/c/functest/+/69888

Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>